ALTER TABLE "Child" ADD COLUMN "stopLabel" TEXT,
ADD COLUMN "homeLat" DOUBLE PRECISION,
ADD COLUMN "homeLon" DOUBLE PRECISION;

ALTER TABLE "TransportAssignment" ADD COLUMN "stopOrder" INTEGER NOT NULL DEFAULT 0;
